# Site settings
title: Weihnachtsmarkt Melle
email: muenster@codefor.de
description: > # this means to ignore newlines until "baseurl:"
  Die Weihnachtsmarkt App für den Weihnachtsmarkt Melle.
baseurl: "" # the subpath of your site, e.g. /blog/ Unless empty, should end with a /
url: "" # the base hostname & protocol for your site
twitter_username: codeformuenster
github_username:  codeformuenster
permalink: /staende/:title

### Configurable Keys!

# these keys in the properties of the stalls are considered in the search
searchableProperties:
  - betreiber
  - angebot
  - telefon
  - email
  - label
  - stand
  - typ

# strings used in the app
strings:
  appTitle: Weihnachtsmarkt-App
  appTitleSubTitle: mit Suche!
  appDescriptionText: >
    Diese App erlaubt es, Stände auf dem Weihnachtsmarkt in Melle zu durchsuchen. Einfach Suchbegriff oben ins Suchfeld eingeben. Passende Stände werden dann farblich markiert.
  letsGo: Los gehts!
  initialSearchResultView: Hier erscheinen die Suchergebnisse, einfach oben lostippen!
  noResults: 'Nichts für \"{str}\" gefunden!'
  searchPlaceholder: Angebotssuche
  resetSearchTitle: Suche zurücksetzen
  infoButton: Info

# Map config keys
map:
  center: [52.20258203, 8.33679602]
  zoom: 20
  tileLayerUrl: 'https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png'
  normalColor: '#E0E0E0'
  lowColor: '#B8BCC8'
  highColor: '#ff3322'
  resultColor: '#F57F06'

### Better not change these!

# Build settings
markdown: kramdown
sass:
  style: compressed
exclude: ['bower_components']
host: 0.0.0.0
